### ISSUE TITLE
GPi Case V1 Dpad not registering.

### ISSUE THREAD

**Issue by hartleyshc** [Reesy1979/gpiemu#3]
Pi Zero W 
GPi Case v1
v1.0-beta.1

It seems I am able to change tabs using the L and R buttons. 
"A" works, I am able to launch the sms emulator with it.

Dpad does not register any button presses, Both in the menu and within the sms emulator once its launched.

**Comment by ccarlson71** [comment]
I've observed the same behavior. I hope to dig into the source code a bit next week to see if I can contribute, but I have zero experience with Circle or any Raspberry Pi I/O functionality at all.

**Comment by ccarlson71** [comment]
@hartleyshc , I fixed this issue for myself by switching to "axis" input mode, as described on [this page](https://droix.co.uk/knowledge-base/article/how-to-switch-input-modes-on-retroflag-gpi-case/).

**Comment by hartleyshc** [comment]
@ccarlson71 , thanks! That did it for me, except I had to change mine to Hat mode. 

Never even knew this was a gpi case feature, but it makes sense depending on the type of game the user is playing.

**Comment by ccarlson71** [comment]
Aha—I probably just had that backwards. In any case, input mode was the issue!

**Comment by Reesy1979** [comment]
Didn't even know this was a thing, looks like its the fix - thanks for finding @ccarlson71
